import Head from "next/head";
import FooterC from "./footer";
import NavC from "./nav";
import { useState, useEffect } from "react";
import { motion, useScroll, useSpring } from "framer-motion";
import "animate.css";
import { Fira_Code } from "next/font/google";

const fira = Fira_Code({
  subsets: [
    "cyrillic",
    "cyrillic-ext",
    "greek",
    "greek-ext",
    "latin",
    "latin-ext",
  ],
  weight: ["300", "400", "500", "600", "700"],
});

export default function Layout({ children }) {
  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001,
  });

  useEffect(() => {
    const handleContextmenu = (e) => {
      e.preventDefault();
    };
    document.addEventListener("contextmenu", handleContextmenu);
    return function cleanup() {
      document.removeEventListener("contextmenu", handleContextmenu);
    };
  }, []);

  return (
    <div className={`${fira.className}`}>
      <Head>
        <title>Febriqgal Purnama, S.Kom.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <NavC />

      <motion.div
        className="progress-bar bg-[#094E68] dark:bg-white bottom-0 h-1 z-[99999] rounded-full fixed left-0 right-0 origin-top"
        style={{ scaleX }}
      />

      <main className="min-h-screen px-5 lg:px-[200px]">{children}</main>

      <FooterC />
    </div>
  );
}
