/* eslint-disable @next/next/no-img-element */
import { Button } from "@nextui-org/react";
import { Metadata } from "next";
import Link from "next/link";
import React from "react";
import { AppConfig } from "./_constant/AppConfig";

export const metadata: Metadata = {
  title: `404 - ${AppConfig.title}`,
  description: "Generated by create next app",
};
export default function NotFound404() {
  return (
    <div className="flex flex-col h-screen bg-white">
      <img
        src="https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        alt=""
        className="object-cover w-full h-64"
      />

      <div className="flex items-center justify-center flex-1">
        <div className="max-w-xl px-4 py-8 mx-auto text-center">
          <h1 className="text-2xl font-bold tracking-tight text-gray-900 sm:text-4xl">
            404
          </h1>
          <h1 className="text-2xl font-bold tracking-tight text-gray-900 sm:text-4xl">
            We cant find that page.
          </h1>

          <p className="mt-4 text-gray-500">
            Try searching again, or return home to start from the beginning.
          </p>

          <Button
            variant="shadow"
            color="primary"
            as={Link}
            href="/"
            className="mt-8"
          >
            Go Back Home
          </Button>
        </div>
      </div>
    </div>
  );
}
