import Layout from "@/components/layout";
import Image from "next/image";
import React from "react";
import Gambar1 from "../../../public/gambar1.jpg";
import { Tooltip } from "@nextui-org/react";
import Styles from "../../styles/Home.module.css";
import Head from "next/head";
export default function About() {
  return (
    <Layout>
      <Head>
        <title>About Me - Febriqgal Purnama</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col-reverse lg:flex-row w-full justify-between items-center">
        <div className="w-full lg:pr-16 text-justify">
          <h1 className="lg:text-4xl underline  text-center rounded-lg text-white text-3xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-indigo-200 via-red-200 to-yellow-100">
            Febriqgal Purnama, S.Kom
          </h1>
          <br />
          <h1>
            Laboris cupidatat laborum do sint cillum aute laboris ipsum. Id
            irure et consectetur aliquip commodo aute aute ullamco culpa
            proident. Excepteur cillum labore esse dolore quis in ullamco
            officia. Adipisicing voluptate duis nisi Lorem aliquip id. Sit
            proident officia eiusmod velit. Aliquip pariatur sint est eiusmod in
            reprehenderit pariatur amet voluptate ullamco occaecat est. Laborum
            aute culpa officia in dolor eu consectetur nisi. Aute Lorem
            adipisicing nisi adipisicing eiusmod duis in incididunt non enim in
            tempor et labore. Sint laborum ut commodo ex magna. Lorem non ipsum
            aute culpa. Ullamco dolor cupidatat aute nisi. Id anim id fugiat
            duis cupidatat non sunt sit quis. Mollit nulla aliqua qui est
            ullamco exercitation consequat id eu eu anim exercitation velit
            voluptate. Pariatur fugiat consequat cillum sunt sunt. Esse occaecat
            ipsum in do ut dolor nulla est eiusmod aute sint.
          </h1>
       
        </div>
        <br />
        <div className="h-[460px] aspect-square overflow-hidden rounded-lg border">
          <Image
            className="scale-[2.5] hover:scale-[2.9] duration-500 hover:rotate-2 transition-transform translate-x-3"
            src={Gambar1}
            alt={"Febriqgal"}
          />
        </div>
      </div>
    </Layout>
  );
}
