import Layout from "@/components/layout";
import Image from "next/image";
import Gambar1 from "../../../public/gambar1.jpg";
import Head from "next/head";
export default function About() {
  return (
    <Layout>
      <Head>
        <title>About Me - Febriqgal Purnama, S.Kom.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <div className="flex mt-[100px] flex-col-reverse items-center justify-between w-full lg:flex-row">
        <div className="w-full text-justify lg:pr-16">
          <h1 className="lg:text-4xl text-center text-3xl font-black bg-clip-text text-transparent box-decoration-slice bg-gradient-to-r from-slate-400  to-[#0A4D68]">
            Febriqgal Purnama, S.Kom.
          </h1>

          <br />

          <h1>
            Hello! I&apos;m Febriqgal. I graduated from a private university in
            Padang city in 2023, I started studying programming in May 2020,
            when the pandemic started. There wasn&apos;t much for me to do at
            the time, so I decided to teach myself programming on YouTube, then
            started watching a lot of YouTube videos to learn more about
            programming, specifically{" "}
            <span className="underline underline-offset-4 decoration-dotted">
              Web Development
            </span>
            , and{" "}
            <span className="underline underline-offset-4 decoration-dotted">
              {" "}
              Mobile Development
            </span>
            .
            <br />
            <br />
            There is a lot of stuff and technology to learn in programming and I
            am motivated to learn as much as I can. I enjoy learning something
            new and getting feedback to improve and grow.
          </h1>
          <br />
          <h1>
            On this website, I will write to showcase my portfolio. I believe
            that writing down what I&apos;ve learned is the best way to build a{" "}
            <span className="underline underline-offset-4 decoration-dotted">
              Personal Branding
            </span>
          </h1>
          <br />
          <q className="text-xs italic">
            {`Apa yang kita tanam, itu yang akan kita tuai.`}
          </q>
        </div>
        <br />
        <div className="h-[460px] aspect-square overflow-hidden rounded-lg border">
          <Image
            placeholder="blur"
            className="scale-[2.5] hover:scale-[2.9] duration-500 transition-transform translate-x-3"
            src={Gambar1}
            alt={"Febriqgal"}
          />
        </div>
      </div>
    </Layout>
  );
}
