/* eslint-disable @next/next/no-img-element */
import Layout from "@/components/layout";
import Head from "next/head";
export default function Blog() {
  const portfolio = [
    { title: "", img: "" },
    { title: "", img: "" },
    { title: "", img: "" },
    { title: "", img: "" },
    { title: "", img: "" },
    { title: "", img: "" },
    { title: "", img: "" },
    { title: "", img: "" },
    { title: "", img: "" },
    { title: "", img: "" },
  ];
  return (
    <Layout>
      <Head>
        <title>Portfolio - Febriqgal Purnama, S.Kom.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className="mt-[100px]">
        <h1 className="text-center">Coming Soon!</h1>
      </div>
    </Layout>
  );
}
